#!/bin/sh
# run estimator on sgf file.
# needs pachi sources + build (dcnn not needed, but mm best)
# usage: sgf_estimator file.sgf
set -e

die() {  echo "$@"; exit 1;  }

# Need some tools from Pachi
pdir=${HOME}/src/pachi
[ -n "$PACHI_DIR" ] && pdir="$PACHI_DIR"
[ -d "$pdir" ]       || die "pachi directory not found. Please clone repo in ~/src/pachi or set PACHI_DIR."
[ -f "$pdir/pachi" ] || die "build pachi first (dcnn not needed)."
[ -f "$pdir/tools/gtp2board_print" ] || die "update pachi repo, we need gtp2board_print."

dir=`dirname "$0"`/..

# Game rules
rules=`grep 'RU\[' <"$1" | sed -e 's/.*RU\[\([^]]*\)\].*/\1/' | perl -ne 'print lc();'`

board=`mktemp`
ogs=`mktemp`
$pdir/tools/sgf2gtp.pl < "$1" |
$pdir/tools/gtp2board_print   >$board

# Find stuff we need to score from board diagram
komi=`grep "Move:" <$board | sed -e 's/.*Komi: \([0-9.-]\+\).*/\1/'`
handi=`grep "Move:" <$board | sed -e 's/.*Handicap: \([0-9]\+\).*/\1/'`
capb=`grep "Move:" <$board | sed -e 's/.*Captures B: \([0-9]\+\).*/\1/'`
capw=`grep "Move:" <$board | sed -e 's/.* W: \([0-9]\+\).*/\1/'`

$dir/tools/board_print_to_ogs  <$board >$ogs
$dir/estimator $ogs |
$dir/score_game -r $rules -k $komi -a $handi -b $capb -w $capw
rm $board $ogs
