#!/bin/sh
# generic pachi score-estimator
set -e

dir=`dirname "$0"`

die() {  echo "$@"; exit 1;  }

# Need Pachi and tools
pdir="$dir/pachi"
[ -d "$pdir" ]       || die "pachi directory not found. clone or symlink repo here first."
[ -f "$pdir/pachi" ] || die "build pachi first (dcnn not needed)."

dir=`dirname "$0"`

# Save initial ascii board
board=`mktemp`
$dir/tools/tunit_to_board_print <"$1" >$board
cat "$1"; echo ""; echo ""   # print board and header

# Convert to t-unit, pass to pachi and get ownermap
tunit=`mktemp`
( $pdir/tools/board_print_to_tunit  <$board
  echo "moggy status C4 X"    ) |
perl -ne '!$last && s/X /X\)/ && ($last=1); print;'  >$tunit      # add some last move ...  XXX if no black stone ...
( cd $pdir && ./pachi -u $tunit  2>&1 >/dev/null ) |              # just keep stderr
tac | grep -m 1 -B 30 'Move:' | tac                |              # keep ownermap
$dir/tools/board_print_to_ownermap

rm $board $tunit
