#!/bin/bash
# turn a gtp engine into a score estimator (only for scoring finished games)
# usage: estimator file.game

dir="`dirname $0`"
engine="$dir/run_pachi"
options="--accurate-scoring --nodcnn --nojoseki --nopattern"

file="$1"
die() {  echo "$@"; exit 1;  }
[ -f $engine ] || die "couldn't find engine '$engine'"
[ -f $dir/show_ownermap ] || die "show_ownermap missing"

time=`mktemp`
out=`mktemp`
#err=`mktemp`

run_engine()
{
    $dir/tools/tunit_to_board_print < "$file" |
	( $dir/tools/board_print_to_gtp; echo "final_status_list dead" ) |
	/usr/bin/time -o $time -f "Engine time: %e s" \
		      $engine $options  >$out # 2>$err
}

run_engine
$dir/show_ownermap "$file" $out

cat $time
rm $time $out  # $err
