#!/usr/bin/perl
# Convert ascii board diagrams from board_print() to ogs estimator output format
# Usage: ./board_print_to_ogs_out
#        copy paste the diagram with header, ^D

use utf8;
binmode STDIN, ":utf8";
binmode STDOUT, ":utf8";

my $ownermap_mode = 0;
my $show_header = 1;

for (; $ARGV[0] =~ m/^-/; shift(@ARGV)) {
    if ($ARGV[0] eq "--ownermap")   {  $ownermap_mode = 1;  }
    if ($ARGV[0] eq "--no-header")  {  $show_header = 0;  }
}

my $size = 0;
foreach my $s (<STDIN>) {
    if ($ownermap_mode) {
	$s =~ s/^[^|]*\|[^|]*\|//;    # skip regular board, just keep ownermap
    }

    $s =~ s/·/./g;  # color diagrams
    if ($s =~ m/^ *([0-9]+) [ |]+(([.oOxX,:][ )])+)[ |]+/) {   
	$s = $2;
	if ($size == 0)	{
	    $size = split("", $s) / 2;
	    if ($show_header) {
		print "height: $size\n";
		print "width: $size\n";
		print "player to move: 1\n";  # XXX
	    }
	}
	$s =~ s/\)/ /g;    # last move mark
	$s =~ s/[.,:]/ /g;
	$s =~ s/[Oo]/_/g;
	$s =~ s/[Xx]/o/g;
#	$s =~ s/ *$//;
	print "$s\n";
    }
}
printf "\n\n";
